trigger:
  - main
  - develop
pr:
  - develop
  - main

variables:
  ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    NX_BRANCH: 'main'
  ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:
    NX_BRANCH: $(System.PullRequest.PullRequestNumber)

jobs:
  - job: main
    pool:
      vmImage: 'ubuntu-latest'
    condition: ne(variables['Build.Reason'], 'PullRequest')
    steps:
      - script: npm i
      - script: npx nx affected --base=HEAD~1 --target=build --parallel=3
      - script: npx nx affected --base=HEAD~1 --target=test --parallel=2

  - job: pr
    pool:
      vmImage: 'ubuntu-latest'
    condition: eq(variables['Build.Reason'], 'PullRequest')
    steps:
      - script: npm i
      - script: npx nx affected --target=build --parallel=3
      - script: npx nx affected --target=test --parallel=2
