apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-mobile
  labels:
    app: front-mobile
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-mobile
  template:
    metadata:
      labels:
        app: front-mobile
    spec:
      containers:
        - name: front-mobile
          image: front-mobile:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

          resources:
            requests:
              memory: "2Gi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: front-mobile
spec:
  type: NodePort
  selector:
    app: front-mobile
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
      nodePort: 30000

