apiVersion: apps/v1
kind: Deployment
metadata:
  name: integrationtesting
  labels:
    app: integrationtesting
spec:
  replicas: 2
  selector:
    matchLabels:
      app: integrationtesting
  template:
    metadata:
      labels:
        app: integrationtesting
    spec:
      containers:
        - name: integrationtesting
          image: integrationtesting:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

          resources:
            requests:
              memory: "2Gi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: integrationtesting
spec:
  type: NodePort
  selector:
    app: integrationtesting
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
      nodePort: 30004

