apiVersion: apps/v1
kind: Deployment
metadata:
  name: quizz
  labels:
    app: quizz
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quizz
  template:
    metadata:
      labels:
        app: quizz
    spec:
      containers:
        - name: quizz
          image: quizz:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

          resources:
            requests:
              memory: "2Gi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: quizz
spec:
  type: NodePort
  selector:
    app: quizz
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
      nodePort: 30000

