spring:
  profiles:
    group:
      default: dev, common
      prod: prod, common
---
server:
  port : 8080

spring:
  cloud:
    gateway:
      routes:
        - predicates:
            - Path=/stats/**
          filters:
            - StripPrefix=1
          uri: "http://localhost:8086"
        - predicates:
            - Path=/gamification/**
          filters:
                - StripPrefix=1
          uri: "http://localhost:8083"
        - predicates:
            - Path=/quizz/**
          filters:
                - StripPrefix=1
          uri: "http://localhost:8085"

