spring:
    datasource:
      url: jdbc:mysql://localhost:3306/oauth?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Jakarta&useSSL=false
      username: root
      password: root
    jpa:
      generate-ddl: true
      show-sql: true
      hibernate:
        ddl-auto: validate
      properties:
        hibernate:
          format_sql: true
    user:
      datasource:
        driver-class-name: com.mysql.jdbc.Driver
