name: authentication_repository
description: authentication repository
version: 0.0.1
homepage: https://github.com/esgi-lyon/flutter-myaccount


environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"
dependencies: 
  equatable: ^2.0.3
  ffi: ^2.0.1
  local_auth: ^2.1.0

# dependencies: {}
# dev_dependencies: {}
