name: Build and run tests

on:
  push:
    branches: ['**']

jobs:
  test:
    strategy:
      matrix:
        java: [ 17 ]
        os: [ ubuntu-latest ]
    name: Tests - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: develop
      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: 'gradle'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: pnpm nx affected --target=format-check --parallel=5
      - run: pnpm nx affected --target=test --parallel=2
      - run: pnpm nx affected --target=build --parallel=3
