name: Bump version and release

on:
  push:
    branches:
      - 'master'
      - 'develop'

jobs:
  artifact:
    name: Publish - GitHub Packages
    if: >
      contains(github.event.head_commit.message, '[skip-release]') == false
      && contains(github.event.pull_request.labels.*.name, 'skip-release') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: log commit in common
        run: |
          git fetch origin;
          [[ -z $(git branch -a --list origin/develop) ]] && exit 0;
          [[ $(git rev-parse --verify HEAD) = $(git rev-parse --verify origin/develop) ]] \
           && echo 'History OK' && exit 0 || echo "history don't match with pre-release" && exit 1;

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: semver plugins
        run: nx affected --target version
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
